## Build docker Images in Kaniko with GitLab CI
# This snippet builds docker images with Kaniko in a very default GitLab environment
# CI_REGISTRY_USER, CI_REGISTRY and CI_REGISTRY_PASSWORD are predefined in GitLab

variables:
  IMAGE_TAG: "latest"
  KANIKO_CONTEXT: "${CI_PROJECT_DIR}"
  DESTINATION: "${CI_REGISTRY_IMAGE}:${IMAGE_TAG}"
  DOCKERFILE: Dockerfile
  PRELOAD: "false"
  PRELOAD_IMAGE: ""

.kaniko:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.dockerse
    - |-
      cat >${DOCKER_CONFIG}/config.json <<EOF
      {
        "auths": {
          "${CI_REGISTRY}": {
            "username":"$CI_REGISTRY_USER",
            "password":"$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
  script:
    - |
      if [ "$PRELOAD" == "true" ]; then
         /kaniko/warmer -f --image=$PRELOAD_IMAGE
      fi
    - /kaniko/executor
      --dockerfile ${DOCKERFILE}
      --context ${KANIKO_CONTEXT}
      --destination $DESTINATION
      --snapshotMode=redo
      --cache=false
      --use-new-run